Repository Pixel-Null/BureauOnbeperkteZaken, pull requests merged in 2022-06, with the labels that each got.

#62 Bug/fix metadata slug
  app/Http/Controllers/MetaDataController.php
  database/seeders/MetaSeeder.php
  resources/views/layouts/admin.blade.php
  resources/views/layouts/menu.blade.php
  routes/panel.php
Labels: bug

#63 Fixed the error
  routes/auth.php
  tests/Feature/RoutingTest.php
Labels: bug

#66 Feat/boz 65 over ons pagina
  app/Http/Controllers/OveronsController
  app/Http/Controllers/OveronsController.php
  resources/views/overons.blade.php
  routes/web.php
  tests/Feature/RoutingTest.php
Labels: bug

#69 Boz 106/meerjarenplan scaling
  public/stylesheets/stylesheet.css
  resources/views/bureauonbeperktezaken/samenwerkingen.blade.php
  resources/views/contact.blade.php
Labels: enhancement

#67 Bug/fix laravel errors
  app/Exceptions/Handler.php
  resources/lang/en/errors.php
  resources/lang/nl/errors.php
  resources/views/errors/500.blade.php
Labels: enhancement

#70 Boz 106 als gebruiker wil ik alle paginas goed schalen zodat ik op zowel mijn computer als mijn telefoon de website kan bezoeken
  public/stylesheets/stylesheet.css
  resources/views/bureauonbeperktezaken/samenwerkingen.blade.php
  resources/views/components/page/base-novid.blade.php
  resources/views/components/page/fullwidth-novid.blade.php
  resources/views/contact.blade.php
  resources/views/jarenplan.blade.php
  resources/views/overons.blade.php
  resources/views/projects.blade.php
Labels: enhancement

#72 Feat/boz 105 home pagina verbetering
  database/seeders/MetaSeeder.php
  public/img/BOZ_banner.JPG
  public/img/BOZ_banner.JPGZone.Identifier
  public/img/BOZ_logo.JPG
  public/img/BOZ_logo.JPGZone.Identifier
  public/stylesheets/stylesheet.css
  resources/views/app/home.blade.php
  resources/views/bureauonbeperktezaken/samenwerkingen.blade.php
  resources/views/contact.blade.php
  resources/views/jarenplan.blade.php
Labels: enhancement

#71 Create pull_request_template.md
  docs/pull_request_template.md
Labels: documentation
